-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS I INNER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE (I.SEX_UPON_INTAKE = 'Intact Female' OR I.SEX_UPON_INTAKE = 'Intact Male')
AND (O.SEX_UPON_OUTCOME = 'Spayed Female' OR O.SEX_UPON_OUTCOME = 'Spayed Male'
OR O.SEX_UPON_OUTCOME = 'Neutered Female' OR O.SEX_UPON_OUTCOME = 'Neutered Male')
ORDER BY O.ANIMAL_ID ASC;