-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR FROM FIRST_HALF INNER JOIN ICECREAM_INFO ON FIRST_HALF.FLAVOR =
ICECREAM_INFO.FLAVOR AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based' WHERE TOTAL_ORDER > 3000 ORDER BY TOTAL_ORDER DESC;