-- 코드를 작성해주세요
SELECT SUM(SCORE) AS `SCORE`, B.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES A INNER JOIN HR_GRADE B ON A.EMP_NO = B.EMP_NO
WHERE B.YEAR = 2022
GROUP BY B.EMP_NO
ORDER BY SCORE DESC LIMIT 1;